 <footer>
       
    </footer><!--/#footer-->

    <script src="<?=$this->basePath() . '/public/js/adminjs/jquery.js'?> "></script>
    <script src="<?=$this->basePath() . '/public/js/adminjs/html5shiv.js'?> "></script>
    <script src="<?=$this->basePath() . '/public/js/adminjs/bootstrap.min.js'?>"></script>
    <script src="<?=$this->basePath() . '/public/js/adminjs/jquery.prettyPhoto.js'?>"></script>
    <script src="<?=$this->basePath() . '/public/js/adminjs/jquery.isotope.min.js'?>"></script>
    <script src="<?=$this->basePath() . '/public/js/adminjs/main.js'?>"></script>
    <script src="<?=$this->basePath() . '/public/js/adminjs/wow.min.js'?>"></script>
    
    
    <link href="<?=$this->basePath() . '/public/css/admincss/font-awesome.min.css'?>" rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/admincss/bootstrap.min.css'?>" rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/admincss/animate.min.css'?>" rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/admincss/prettyPhoto.css'?> " rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/admincss/main.css'?>" rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/admincss/responsive.css'?>" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="<?=$this->basePath() . '/public/img/adminimages/ico/favicon.ico'?>">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?=$this->basePath() . '/public/img/adminimages/ico/apple-touch-icon-144-precomposed.png'?>">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?=$this->basePath() . '/public/img/adminimages/ico/apple-touch-icon-114-precomposed.png'?>">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?=$this->basePath() . '/public/img/adminimages/ico/apple-touch-icon-72-precomposed.png'?>">
    <link rel="apple-touch-icon-precomposed" href="<?=$this->basePath() . '/public/img/adminimages/ico/apple-touch-icon-57-precomposed.png'?>">
</body>
</html>