 <footer id="footer" class="midnight-blue">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2016 <a target="_blank" href="#" title="">HireApplicants</a>. All Rights Reserved.
                </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                        <li><a href="<?=$GLOBALS['SITE_APP_URL']?>">Home</a></li>
                        <li><a href="<?=$GLOBALS['SITE_APP_URL']?>/aboutus">About Us</a></li>
                        <li><a href="<?=$GLOBALS['SITE_APP_URL']?>/faq">Faq</a></li>
                        <li><a href="<?=$GLOBALS['SITE_APP_URL']?>/contactus">Contact Us</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->

    <!--script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>-->
    <script src="<?=$this->basePath() . '/public/js/companyjs/jquery.prettyPhoto.js'?>"></script>
    <script src="<?=$this->basePath() . '/public/js/companyjs/jquery.isotope.min.js'?>"></script>
    <script src="<?=$this->basePath() . '/public/js/companyjs/main.js'?>"></script>
    <script src="<?=$this->basePath() . '/public/js/companyjs/wow.min.js'?>"></script>
    
    
    <link href="<?=$this->basePath() . '/public/css/companycss/font-awesome.min.css'?>" rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/companycss/animate.min.css'?>" rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/companycss/prettyPhoto.css'?> " rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/companycss/main.css'?>" rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/companycss/responsive.css'?>" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="<?=$this->basePath() . '/public/img/companyimages/ico/favicon.ico'?>">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?=$this->basePath() . '/public/img/companyimages/ico/apple-touch-icon-144-precomposed.png'?>">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?=$this->basePath() . '/public/img/companyimages/ico/apple-touch-icon-114-precomposed.png'?>">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?=$this->basePath() . '/public/img/companyimages/ico/apple-touch-icon-72-precomposed.png'?>">
    <link rel="apple-touch-icon-precomposed" href="<?=$this->basePath() . '/public/img/companyimages/ico/apple-touch-icon-57-precomposed.png'?>">
</body>
</html>