 <footer id="footer" class="midnight-blue">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2016 <a target="_blank" href="#" title="">HireApplicants</a>. All Rights Reserved.
                </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                        <li><a href="<?=$GLOBALS['SITE_APP_URL']?>">Home</a></li>
                        <li><a href="<?=$GLOBALS['SITE_APP_URL']?>/aboutus">About Us</a></li>
                        <li><a href="<?=$GLOBALS['SITE_APP_URL']?>/faq">Faq</a></li>
                        <li><a href="<?=$GLOBALS['SITE_APP_URL']?>/contactus">Contact Us</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->
</body>
</html>