<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | Hireapplicants</title>
	
	<!-- core CSS -->
   <!-- <link href="css/bootstrap.min.css" rel="stylesheet">-->
    
</head><!--/head-->

<body class="homepage">

    <header id="header">
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-xs-4">
                        <div class="top-number"><p><i class="fa fa-phone-square"></i>  +919810669912</p></div>
                    </div>
                    <div class="col-sm-6 col-xs-8">
                       <div class="social">
                            <ul class="social-share">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li> 
                               
                            </ul>
                            
                       </div>
                    </div>
                </div>
            </div><!--/.container-->
        </div><!--/.top-bar-->

        <nav class="navbar navbar-inverse" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?=$GLOBALS['SITE_APP_URL']?>"><img src=" <?=$this->basePath() . '/public/img/companyimages/logo.png'?> " alt="logo"></a>
                </div>
				
                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?=$GLOBALS['SITE_APP_URL']?>">Home</a></li>
                        <li><a href="<?=$GLOBALS['SITE_APP_URL']?>/aboutus">About Us</a></li>
                        <li><a href="<?=$GLOBALS['SITE_APP_URL']?>/services">Services</a></li>
			<li><a href="<?=$GLOBALS['SITE_APP_URL']?>/pricing">Pricing</a></li>
                        <li><a href="<?=$GLOBALS['SITE_APP_URL']?>/faq">FAQ</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Signup/Signin <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?=$GLOBALS['SITE_APP_URL']?>/signup">Signup</a></li>
                                <li><a href="<?=$GLOBALS['SITE_APP_URL']?>/signin">Signin</a></li>
                                
                            </ul>
                        </li>
                      
                        <li><a href="<?=$GLOBALS['SITE_APP_URL']?>/contactus">Contact</a></li>                        
                    </ul>
                </div>
            </div><!--/.container-->
        </nav><!--/nav-->
		
    </header><!--/header-->