<section id="error" class="container text-center">
       
        <div id="signupbox" margin-top:50px" class="mainbox col-md-10 col-md-offset-1 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <div class="panel-title">Sign Up</div>
                            <div style="float:right; font-size: 85%; position: relative; top:-10px"><a id="signinlink" href="<?=$GLOBALS['SITE_APP_URL']?>/signin" >Sign In</a></div>
                        </div>  
                        <div class="panel-body" >
                            <form id="signupform" class="form-horizontal" role="form">
                                
                                <div id="signupalert" style="display:none" class="alert alert-danger">
                                    <p>Error:</p>
                                    <span></span>
                                </div>
                                   <div class="form-group">
                                    <label for="companyname" class="col-md-3 control-label">Company Name</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="companyname" placeholder="Company Name">
                                    </div>
                                </div>
								 <div class="form-group">
                                    <label for="companywebsite URL" class="col-md-3 control-label">Company Website URL </label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="companywebsite" placeholder="Company Website URL ">
                                    </div>
                                </div> 
								 <div class="form-group">
                                    <label for="country" class="col-md-3 control-label">Country </label>
                                    <div class="col-md-9">
                                       	<select class="form-control" id="" name="country">
												<option>Select Country</option>
												<option>India</option>
												
										</select>
                                    </div>
                                </div> 
								<div class="form-group">
                                    <label for="state" class="col-md-3 control-label">State </label>
                                    <div class="col-md-9">
                                       	<select class="form-control" id="" name="state">
												<option>Select State</option>
												<option>UP</option>
												
										</select>
                                    </div>
                                </div> 
								<div class="form-group">
                                    <label for="city" class="col-md-3 control-label">City </label>
                                    <div class="col-md-9">
                                       	<select class="form-control" id="" name="city">
												<option>Select City</option>
												<option>Noida</option>
												
										</select>
                                    </div>
                                </div> 
								 <div class="form-group">
                                    <label for="companyaddress" class="col-md-3 control-label">Company Address </label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="companyaddress" placeholder="Company Address">
                                    </div>
                                </div>
								<div class="form-group">
                                    <label for="zipcode" class="col-md-3 control-label">Zip Code </label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="zipcode" placeholder="Zip Code">
                                    </div>
                                </div>
								<div class="form-group">
                                    <label for="comanymailid" class="col-md-3 control-label">Comany Mail Id </label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="comanymailid" placeholder="Comany Mail Id">
                                    </div>
                                </div>
								<div class="form-group">
                                    <label for="companyphonenumber" class="col-md-3 control-label">Company Phone Number </label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="companyphonenumber" placeholder="Company Phone Number">
                                    </div>
                                </div>
								<div class="form-group">
                                    <label for="alternativemobilenumber" class="col-md-3 control-label">Alternative Mobile Number </label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="alternativemobilenumber" placeholder="Alternative Mobile Number">
                                    </div>
                                </div>
                                
                                 <div class="form-group">
                                    <label for="usertype" class="col-md-3 control-label">User Type</label>
                                    <div class="col-md-9">
                                       	<select class="form-control" id="" name="usertype">
												<option>Select User Type</option>
												<option>Consultant</option>
												<option>Company</option>
												
										</select>
                                    </div>
                                </div> 
                                
                                    
                                <div class="form-group">
                                    <label for="firstname" class="col-md-3 control-label">First Name</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="firstname" placeholder="First Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="lastname" class="col-md-3 control-label">Last Name</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="lastname" placeholder="Last Name">
                                    </div>
                                </div>
                                
                                 <div class="form-group">
                                    <label for="optioncontact" class="col-md-3 control-label">Options to contact with your Company</label>
                                    <div class="col-md-9">
                                       	<select class="form-control" id="" name="optioncontact">
												<option>Select Option</option>
												<option>Phone</option>
												<option>Email</option>
												<option>Both</option>
												
										</select>
                                    </div>
                                </div>    
								<div class="form-group">
                                    <label for="besttimecontact" class="col-md-3 control-label">Best Time to contact</label>
                                    <div class="col-md-9">
                                       	   <input type="text" class="form-control" name="besttimecontact" placeholder="please select time">
                                    </div>
                                </div>    
                               

                                <div class="form-group">
                                    <!-- Button -->                                        
                                    <div class="col-md-offset-3 col-md-9">
                                        <button id="btn-signup" type="button" class="btn btn-info"><i class="icon-hand-right"></i> &nbsp Sign Up</button>
                                        
                                    </div>
                                </div>
                                
                                
                                
                                
                                
                            </form>
                         </div>
                    </div>

               
               
                
         </div> 
    </section><!--/#error-->
