<?php 
echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php /*echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/public/css/style.css')
                        ->prependStylesheet($this->basePath() . '/public/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/public/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath().'/public/js/validate.js')    
            ->prependFile($this->basePath().'/public/js/angular.min.js')    
            ->prependFile($this->basePath() . '/public/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/public/js/jquery.min.js')    
        ; */?>
        <?php echo $this->headScript()
            ->prependFile($this->basePath().'/public/js/validate.js')
            ->prependFile($this->basePath().'/public/js/adminjs/main.js')
            ->prependFile($this->basePath().'/public/js/angular.min.js')
        ; ?>
    </head>
   
    <?php
    echo $this->partial('layout/companylayout/header');
    ?>
    
        
        
            <?php 
            die('sss');echo $this->content; ?>
            <?php
    echo $this->partial('layout/companylayout/footer');
    ?>        
               
        <?php echo $this->inlineScript() ?>
 
</html>
